spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:java_test_app}
    password: ${DB_PASSWORD:password}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
